version: '3.1'
services:
  app:
    image: ayushhpatel/my-trade-service:latest
    environment:
      # Explicitly set the DATABASE_URL to use SQLite (optional since the code already defaults to it)
      DATABASE_URL: "sqlite:///./orders.db"
    ports:
      - "8001:8000"
