name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: docker build -t ayushhpatel/my-trade-service:latest .

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ayushhpatel/my-trade-service:latest

      # Step 5: Deploy to EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to your project directory on EC2 (adjust this path as needed)
            cd /path/to/your/project
            # Pull the latest image from Docker Hub
            docker pull ayushhpatel/my-trade-service:latest
            # Stop and remove any running container (if exists)
            docker stop my-trade-service || true
            docker rm my-trade-service || true
            # Run the new container (adjust port mapping if needed)
            docker run -d -p 8000:8000 --name my-trade-service ayushhpatel/my-trade-service:latest
